### ISSUE TITLE
add react-error-overlay

### ISSUE THREAD

**Issue by jsjoeio** [sw-yx/create-react-app-parcel#20]
### Description 
Errors are not being handled properly. I created a <Button /> component and inside the component, I'm using `{props.text}` instead of `{this.props.text}` and it renders a blank page and does not show the error. 

### Steps to Reproduce:
1. `crap myapp`
2. `yarn start`
3. create `Button.js` file with the following:

```javascript
import React, { Component } from 'react'

class Button extends Component {
  render() {
    return <button>{props.text}</button>
  }
}

export default Button

```
4. inside `App.js` add `<Button text="hello"/>`
5. navigate to `http://localhost:1234/`

#### Expected:
An error to be shown in the browser/browser console or the terminal 

#### Actual Result:
The app does not render and shows a white screen with nothing in the browser console or the terminal.

#### Screenshots:
<img width="1552" alt="screen shot 2018-08-06 at 7 08 12 pm" src="https://user-images.githubusercontent.com/3806031/43750208-1c5a6738-99ac-11e8-9c9b-b0f6fceab3b1.png">
<img width="1002" alt="screen shot 2018-08-06 at 7 08 15 pm" src="https://user-images.githubusercontent.com/3806031/43750209-1c8315b6-99ac-11e8-90c6-b8b697221189.png">

**Comment by sw-yx** [comment]
thanks for the report! trying to replicate

**Comment by sw-yx** [comment]
i see an error in the terminal here:

![plsdelete](https://user-images.githubusercontent.com/6764957/43950670-ee39d4be-9c5e-11e8-90c1-aa9274e8d7ba.png)


it would not show up in your terminal because its a runtime not a buildtime error.

so what we're really getting at here is the lack of react-error-overlay which is based on webpack in create-react-app. i agree that it is something we miss and i need to add at some point for a slightly better UX. gonna leave this open as a tracking issue

**Comment by jsjoeio** [comment]
Ah, I think I had something turned off in my console and that's why I didn't see it. Gotcha! Well if you're interested in pair-programming on this, I'm happy to help sometime!

**Comment by sw-yx** [comment]
hey JS Joe! (great name)

im not gonna work on this right now. would take a PR on it, or else i will come back around to it when we do the big rewrite for parcel v2.

**Comment by jsjoeio** [comment]
@sw-yx Thanks!

No worries. We can close it. When it comes time for the big rewrite and need help, let me know!
