### ISSUE TITLE
Uncaught ReferenceError: Component is not defined

### ISSUE THREAD

**Issue by androidand** [sw-yx/create-react-app-parcel#28]
I wanted to try out C.R.A.P but sadly even the minimal boilerplate example I get from running
crap my-app

cd my-app
npm run build or yarn build

The error in the console for the minified js is 

> Uncaught ReferenceError: Component is not defined

```
      return mj(t, Component),
        jj(t, [{
            key: "render",
            value: function() {
```

Any ideas? I actually started working on a site and discovered this when I wanted to try to build and deploy it.

**Comment by sw-yx** [comment]
hi!

sorry you're experiencing this. I just tried it and i had a different error - `@babel/plugin-proposal-class-properties` wasnt installed. thats easy to fix. I'm not sure about your specific issue - can you install `@babel/plugin-proposal-class-properties` and retry? I cant replicate otherwise, it builds fine for me for now. I'll work on resolving this babel plugin issue.

**Comment by sw-yx** [comment]
The upgrade to babel 7 has been fraught with issues. i just tried pushing a few fixes and the yak shaving still continues on. I'm gonna have to rewrite this again for Parcel v2 so i think for now I will have to put this project on hold and make it very clear in the README that it is not currently supported. very sorry to disappoint and please try again when Parcel v2 is out.

**Comment by sw-yx** [comment]
closing and seeking maintainer! https://github.com/sw-yx/create-react-app-parcel/issues/34
